title: Install Wireless Canon Printer Driver 
description: Visit ij.start canon and enter canon printer model number you want to download. Connect your wireless canon printer using the simple steps at its official website.
